import right_telebot
lSql = ['insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (13, 53, 12, 3,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (14, 53, 0,  4,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (15, 53, 0,  5,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (16, 53, 5,  6,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (17, 53, 1,  7,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (18, 61, 12, 1,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (19, 61, 0,  2,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (20, 61, 12, 3,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (21, 61, 0,  4,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (22, 61, 0,  5,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (23, 61, 5,  6,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (24, 61, 1,  7,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (25, 62, 12, 1,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (26, 62, 0,  2,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (27, 62, 0,  3,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (28, 62, 5,  4,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (29, 62, 1,  5,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (30, 3,  12, 1,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (31, 3,  0,  2,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (32, 3,  0,  3,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (33, 3,  5,  4,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (34, 3,  1,  5,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (35, 4,  12, 1,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (36, 4,  0,  2,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (37, 4,  0,  3,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (38, 4,  5,  4,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (39, 4,  1,  5,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (40, 5,  12, 1,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (41, 5,  0,  2,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (42, 5,  0,  3,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (43, 5,  5,  4,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (44, 5,  1,  5,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (45, 6,  12, 1,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (46, 6,  0,  2,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (47, 6,  0,  3,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (48, 6,  5,  4,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (49, 6,  1,  5,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (50, 7,  12, 1,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (51, 7,  0,  2,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (52, 7,  0,  3,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (53, 7,  5,  4,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (54, 7,  1,  5,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (55, 11, 12, 1,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (56, 11, 0,  2,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (57, 11, 0,  3,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (58, 11, 5,  4,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (59, 11, 1,  5,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (60, 12, 12, 1,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (61, 12, 0,  2,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (62, 12, 0,  3,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (63, 12, 5,  4,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (64, 12, 1,  5,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (65, 13, 12, 1,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (66, 13, 0,  2,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (67, 13, 0,  3,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (68, 13, 5,  4,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (69, 13, 1,  5,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (70, 14, 12, 1,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (71, 14, 0,  2,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (72, 14, 0,  3,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (73, 14, 5,  4,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (74, 14, 1,  5,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (75, 15, 12, 1,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (76, 15, 0,  2,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (77, 15, 0,  3,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (78, 15, 5,  4,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (79, 15, 1,  5,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (80, 16, 12, 1,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (81, 16, 0,  2,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (82, 16, 0,  3,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (83, 16, 5,  4,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (84, 16, 1,  5,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (85, 21, 12, 1,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (86, 21, 0,  2,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (87, 21, 0,  3,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (88, 21, 5,  4,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (89, 21, 1,  5,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (90, 22, 12, 1,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (91, 22, 0,  2,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (92, 22, 0,  3,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (93, 22, 5,  4,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (94, 22, 1,  5,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (95, 23, 12, 1,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (96, 23, 0,  2,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (97, 23, 0,  3,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (98, 23, 5,  4,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (99, 23, 1,  5,  2)' ,
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (100, 31, 12, 1,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (101, 31, 0,  2,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (102, 31, 0,  3,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (103, 31, 5,  4,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (104, 31, 1,  5,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (105, 32, 12, 1,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (106, 32, 0,  2,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (107, 32, 0,  3,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (108, 32, 5,  4,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (109, 32, 1,  5,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (110, 33, 12, 1,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (111, 33, 0,  2,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (112, 33, 0,  3,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (113, 33, 5,  4,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (114, 33, 1,  5,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (115, 34, 12, 1,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (116, 34, 0,  2,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (117, 34, 0,  3,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (118, 34, 5,  4,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (119, 34, 1,  5,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (120, 41, 12, 1,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (121, 41, 0,  2,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (122, 41, 0,  3,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (123, 41, 5,  4,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (124, 41, 1,  5,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (125, 42, 12, 1,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (126, 42, 0,  2,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (127, 42, 0,  3,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (128, 42, 5,  4,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (129, 42, 1,  5,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (130, 43, 12, 1,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (131, 43, 0,  2,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (132, 43, 0,  3,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (133, 43, 5,  4,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (134, 43, 1,  5,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (135, 53, 12, 1,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (136, 53, 0,  2,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (137, 53, 0,  3,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (138, 53, 5,  4,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (139, 53, 1,  5,  2)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (140, 53, 12, 3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (141, 53, 0,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (142, 53, 0,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (143, 53, 5,  6,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (144, 53, 1,  7,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (145, 61, 12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (146, 61, 0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (147, 61, 12, 3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (148, 61, 0,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (149, 61, 0,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (150, 61, 5,  6,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (151, 61, 1,  7,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (152, 62, 12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (153, 62, 0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (154, 62, 0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (155, 62, 5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (156, 62, 1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (157, 3,  12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (158, 3,  0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (159, 3,  0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (160, 3,  5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (161, 3,  1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (162, 4,  12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (163, 4,  0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (164, 4,  0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (165, 4,  5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (166, 4,  1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (167, 5,  12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (168, 5,  0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (169, 5,  0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (170, 5,  5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (171, 5,  1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (172, 6,  12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (173, 6,  0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (174, 6,  0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (175, 6,  5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (176, 6,  1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (177, 7,  12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (178, 7,  0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (179, 7,  0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (180, 7,  5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (181, 7,  1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (182, 11, 12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (183, 11, 0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (184, 11, 0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (185, 11, 5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (186, 11, 1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (187, 12, 12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (188, 12, 0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (189, 12, 0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (190, 12, 5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (191, 12, 1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (192, 13, 12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (193, 13, 0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (194, 13, 0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (195, 13, 5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (196, 13, 1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (197, 14, 12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (198, 14, 0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (199, 14, 0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (200, 14, 5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (201, 14, 1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (202, 15, 12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (203, 15, 0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (204, 15, 0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (205, 15, 5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (206, 15, 1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (207, 16, 12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (208, 16, 0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (209, 16, 0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (210, 16, 5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (211, 16, 1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (212, 21, 12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (213, 21, 0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (214, 21, 0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (215, 21, 5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (216, 21, 1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (217, 22, 12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (218, 22, 0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (219, 22, 0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (220, 22, 5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (221, 22, 1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (222, 23, 12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (223, 23, 0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (224, 23, 0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (225, 23, 5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (226, 23, 1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (227, 31, 12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (228, 31, 0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (229, 31, 0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (230, 31, 5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (231, 31, 1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (232, 32, 12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (233, 32, 0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (234, 32, 0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (235, 32, 5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (236, 32, 1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (237, 33, 12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (238, 33, 0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (239, 33, 0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (240, 33, 5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (241, 33, 1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (242, 34, 12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (243, 34, 0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (244, 34, 0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (245, 34, 5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (246, 34, 1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (247, 41, 12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (248, 41, 0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (249, 41, 0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (250, 41, 5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (251, 41, 1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (252, 42, 12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (253, 42, 0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (254, 42, 0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (255, 42, 5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (256, 42, 1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (257, 43, 12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (258, 43, 0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (259, 43, 0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (260, 43, 5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (261, 43, 1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (262, 53, 12, 1,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (263, 53, 0,  2,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (264, 53, 0,  3,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (265, 53, 5,  4,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (266, 53, 1,  5,  6)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (267, 53, 12, 3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (268, 53, 0,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (269, 53, 0,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (270, 53, 5,  6,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (271, 53, 1,  7,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (272, 61, 12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (273, 61, 0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (274, 61, 12, 3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (275, 61, 0,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (276, 61, 0,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (277, 61, 5,  6,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (278, 61, 1,  7,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (279, 62, 12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (280, 62, 0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (281, 62, 0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (282, 62, 5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (283, 62, 1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (284, 3,  12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (285, 3,  0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (286, 3,  0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (287, 3,  5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (288, 3,  1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (289, 4,  12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (290, 4,  0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (291, 4,  0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (292, 4,  5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (293, 4,  1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (294, 5,  12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (295, 5,  0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (296, 5,  0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (297, 5,  5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (298, 5,  1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (299, 6,  12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (300, 6,  0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (301, 6,  0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (302, 6,  5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (303, 6,  1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (304, 7,  12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (305, 7,  0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (306, 7,  0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (307, 7,  5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (308, 7,  1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (309, 11, 12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (310, 11, 0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (311, 11, 0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (312, 11, 5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (313, 11, 1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (314, 12, 12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (315, 12, 0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (316, 12, 0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (317, 12, 5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (318, 12, 1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (319, 13, 12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (320, 13, 0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (321, 13, 0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (322, 13, 5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (323, 13, 1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (324, 14, 12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (325, 14, 0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (326, 14, 0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (327, 14, 5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (328, 14, 1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (329, 15, 12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (330, 15, 0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (331, 15, 0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (332, 15, 5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (333, 15, 1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (334, 16, 12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (335, 16, 0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (336, 16, 0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (337, 16, 5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (338, 16, 1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (339, 21, 12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (340, 21, 0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (341, 21, 0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (342, 21, 5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (343, 21, 1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (344, 22, 12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (345, 22, 0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (346, 22, 0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (347, 22, 5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (348, 22, 1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (349, 23, 12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (350, 23, 0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (351, 23, 0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (352, 23, 5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (353, 23, 1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (354, 31, 12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (355, 31, 0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (356, 31, 0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (357, 31, 5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (358, 31, 1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (359, 32, 12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (360, 32, 0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (361, 32, 0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (362, 32, 5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (363, 32, 1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (364, 33, 12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (365, 33, 0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (366, 33, 0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (367, 33, 5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (368, 33, 1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (369, 34, 12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (370, 34, 0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (371, 34, 0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (372, 34, 5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (373, 34, 1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (374, 41, 12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (375, 41, 0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (376, 41, 0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (377, 41, 5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (378, 41, 1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (379, 42, 12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (380, 42, 0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (381, 42, 0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (382, 42, 5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (383, 42, 1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (384, 43, 12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (385, 43, 0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (386, 43, 0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (387, 43, 5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (388, 43, 1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (389, 53, 12, 1,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (390, 53, 0,  2,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (391, 53, 0,  3,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (392, 53, 5,  4,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (393, 53, 1,  5,  5)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (394, 53, 12, 3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (395, 53, 0,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (396, 53, 0,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (397, 53, 5,  6,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (398, 53, 1,  7,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (399, 61, 12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (400, 61, 0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (401, 61, 12, 3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (402, 61, 0,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (403, 61, 0,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (404, 61, 5,  6,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (405, 61, 1,  7,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (406, 62, 12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (407, 62, 0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (408, 62, 0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (409, 62, 5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (410, 62, 1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (411, 3,  12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (412, 3,  0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (413, 3,  0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (414, 3,  5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (415, 3,  1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (416, 4,  12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (417, 4,  0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (418, 4,  0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (419, 4,  5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (420, 4,  1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (421, 5,  12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (422, 5,  0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (423, 5,  0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (424, 5,  5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (425, 5,  1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (426, 6,  12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (427, 6,  0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (428, 6,  0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (429, 6,  5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (430, 6,  1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (431, 7,  12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (432, 7,  0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (433, 7,  0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (434, 7,  5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (435, 7,  1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (436, 11, 12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (437, 11, 0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (438, 11, 0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (439, 11, 5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (440, 11, 1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (441, 12, 12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (442, 12, 0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (443, 12, 0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (444, 12, 5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (445, 12, 1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (446, 13, 12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (447, 13, 0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (448, 13, 0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (449, 13, 5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (450, 13, 1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (451, 14, 12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (452, 14, 0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (453, 14, 0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (454, 14, 5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (455, 14, 1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (456, 15, 12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (457, 15, 0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (458, 15, 0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (459, 15, 5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (460, 15, 1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (461, 16, 12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (462, 16, 0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (463, 16, 0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (464, 16, 5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (465, 16, 1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (466, 21, 12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (467, 21, 0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (468, 21, 0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (469, 21, 5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (470, 21, 1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (471, 22, 12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (472, 22, 0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (473, 22, 0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (474, 22, 5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (475, 22, 1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (476, 23, 12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (477, 23, 0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (478, 23, 0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (479, 23, 5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (480, 23, 1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (481, 31, 12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (482, 31, 0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (483, 31, 0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (484, 31, 5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (485, 31, 1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (486, 32, 12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (487, 32, 0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (488, 32, 0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (489, 32, 5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (490, 32, 1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (491, 33, 12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (492, 33, 0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (493, 33, 0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (494, 33, 5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (495, 33, 1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (496, 34, 12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (497, 34, 0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (498, 34, 0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (499, 34, 5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (500, 34, 1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (501, 41, 12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (502, 41, 0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (503, 41, 0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (504, 41, 5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (505, 41, 1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (506, 42, 12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (507, 42, 0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (508, 42, 0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (509, 42, 5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (510, 42, 1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (511, 43, 12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (512, 43, 0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (513, 43, 0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (514, 43, 5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (515, 43, 1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (516, 53, 12, 1,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (517, 53, 0,  2,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (518, 53, 0,  3,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (519, 53, 5,  4,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (520, 53, 1,  5,  4)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (521, 53, 12, 3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (522, 53, 0,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (523, 53, 0,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (524, 53, 5,  6,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (525, 53, 1,  7,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (526, 61, 12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (527, 61, 0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (528, 61, 12, 3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (529, 61, 0,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (530, 61, 0,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (531, 61, 5,  6,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (532, 61, 1,  7,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (533, 62, 12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (534, 62, 0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (535, 62, 0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (536, 62, 5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (537, 62, 1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (538, 3,  12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (539, 3,  0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (540, 3,  0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (541, 3,  5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (542, 3,  1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (543, 4,  12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (544, 4,  0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (545, 4,  0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (546, 4,  5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (547, 4,  1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (548, 5,  12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (549, 5,  0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (550, 5,  0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (551, 5,  5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (552, 5,  1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (553, 6,  12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (554, 6,  0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (555, 6,  0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (556, 6,  5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (557, 6,  1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (558, 7,  12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (559, 7,  0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (560, 7,  0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (561, 7,  5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (562, 7,  1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (563, 11, 12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (564, 11, 0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (565, 11, 0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (566, 11, 5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (567, 11, 1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (568, 12, 12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (569, 12, 0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (570, 12, 0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (571, 12, 5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (572, 12, 1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (573, 13, 12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (574, 13, 0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (575, 13, 0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (576, 13, 5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (577, 13, 1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (578, 14, 12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (579, 14, 0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (580, 14, 0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (581, 14, 5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (582, 14, 1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (583, 15, 12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (584, 15, 0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (585, 15, 0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (586, 15, 5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (587, 15, 1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (588, 16, 12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (589, 16, 0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (590, 16, 0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (591, 16, 5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (592, 16, 1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (593, 21, 12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (594, 21, 0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (595, 21, 0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (596, 21, 5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (597, 21, 1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (598, 22, 12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (599, 22, 0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (600, 22, 0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (601, 22, 5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (602, 22, 1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (603, 23, 12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (604, 23, 0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (605, 23, 0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (606, 23, 5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (607, 23, 1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (608, 31, 12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (609, 31, 0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (610, 31, 0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (611, 31, 5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (612, 31, 1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (613, 32, 12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (614, 32, 0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (615, 32, 0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (616, 32, 5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (617, 32, 1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (618, 33, 12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (619, 33, 0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (620, 33, 0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (621, 33, 5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (622, 33, 1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (623, 34, 12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (624, 34, 0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (625, 34, 0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (626, 34, 5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (627, 34, 1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (628, 41, 12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (629, 41, 0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (630, 41, 0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (631, 41, 5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (632, 41, 1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (633, 42, 12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (634, 42, 0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (635, 42, 0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (636, 42, 5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (637, 42, 1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (638, 43, 12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (639, 43, 0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (640, 43, 0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (641, 43, 5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (642, 43, 1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (643, 53, 12, 1,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (644, 53, 0,  2,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (645, 53, 0,  3,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (646, 53, 5,  4,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (647, 53, 1,  5,  3)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (648, 53, 12, 3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (649, 53, 0,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (650, 53, 0,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (651, 53, 5,  6,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (652, 53, 1,  7,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (653, 61, 12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (654, 61, 0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (655, 61, 12, 3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (656, 61, 0,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (657, 61, 0,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (658, 61, 5,  6,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (659, 61, 1,  7,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (660, 62, 12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (661, 62, 0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (662, 62, 0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (663, 62, 5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (664, 62, 1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (665, 3,  12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (666, 3,  0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (667, 3,  0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (668, 3,  5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (669, 3,  1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (670, 4,  12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (671, 4,  0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (672, 4,  0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (673, 4,  5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (674, 4,  1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (675, 5,  12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (676, 5,  0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (677, 5,  0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (678, 5,  5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (679, 5,  1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (680, 6,  12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (681, 6,  0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (682, 6,  0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (683, 6,  5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (684, 6,  1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (685, 7,  12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (686, 7,  0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (687, 7,  0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (688, 7,  5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (689, 7,  1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (690, 11, 12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (691, 11, 0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (692, 11, 0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (693, 11, 5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (694, 11, 1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (695, 12, 12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (696, 12, 0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (697, 12, 0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (698, 12, 5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (699, 12, 1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (700, 13, 12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (701, 13, 0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (702, 13, 0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (703, 13, 5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (704, 13, 1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (705, 14, 12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (706, 14, 0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (707, 14, 0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (708, 14, 5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (709, 14, 1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (710, 15, 12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (711, 15, 0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (712, 15, 0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (713, 15, 5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (714, 15, 1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (715, 16, 12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (716, 16, 0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (717, 16, 0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (718, 16, 5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (719, 16, 1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (720, 21, 12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (721, 21, 0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (722, 21, 0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (723, 21, 5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (724, 21, 1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (725, 22, 12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (726, 22, 0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (727, 22, 0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (728, 22, 5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (729, 22, 1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (730, 23, 12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (731, 23, 0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (732, 23, 0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (733, 23, 5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (734, 23, 1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (735, 31, 12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (736, 31, 0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (737, 31, 0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (738, 31, 5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (739, 31, 1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (740, 32, 12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (741, 32, 0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (742, 32, 0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (743, 32, 5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (744, 32, 1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (745, 33, 12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (746, 33, 0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (747, 33, 0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (748, 33, 5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (749, 33, 1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (750, 34, 12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (751, 34, 0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (752, 34, 0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (753, 34, 5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (754, 34, 1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (755, 41, 12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (756, 41, 0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (757, 41, 0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (758, 41, 5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (759, 41, 1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (760, 42, 12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (761, 42, 0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (762, 42, 0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (763, 42, 5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (764, 42, 1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (765, 43, 12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (766, 43, 0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (767, 43, 0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (768, 43, 5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (769, 43, 1,  5,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (770, 53, 12, 1,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (771, 53, 0,  2,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (772, 53, 0,  3,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (773, 53, 5,  4,  1)',
 'insert into timetable (id, class_id, lesson_subject_id, lesson_index, lesson_day_id) values (774, 53, 1,  5,  1)']

MyConnect = right_telebot.conn
for sStr in lSql:
    bResult = right_telebot.exec_sql(MyConnect, sStr)
    print(sStr, bResult)
    MyConnect.commit()

